import { useEffect, useState } from "react";
import Layout from "../components/Layout";
import { Status, Empty } from "../components/PageHeader";
import { apiGet, apiPost, apiPut } from "../lib/api";
import toast from "react-hot-toast";
import {
 Lightbulb,
 CheckCircle,
 Package,
 Tag,
 Star,
 BarChart2,
 Filter,
} from "lucide-react";

const PRIORITY_CONFIG = {
 critique: {
 label: "Critical priority",
 tone: "clay",
 border: "bg-clay/5",
 },
 haute: { label: "High priority", tone: "ember", border: "bg-ember-500/5" },
 moyenne: { label: "Medium priority", tone: "olive", border: "bg-olive/5" },
 basse: { label: "Low priority", tone: "steel", border: "" },
};

// Fallback for unknown priorities
const DEFAULT_PRIORITY = PRIORITY_CONFIG.basse;

const CATEGORY_CONFIG = {
 stock: { label: "Stock", icon: Package, tone: "ember" },
 promotion: { label: "Promotion", icon: Tag, tone: "olive" },
 service_client: { label: "Customer service", icon: Star, tone: "ember" },
 analyse: { label: "Analysis", icon: BarChart2, tone: "steel" },
};

export default function RecommendationsPage() {
 const [recs, setRecs] = useState([]);
 const [filter, setFilter] = useState("tous");
 const [loading, setLoading] = useState(true);

 useEffect(() => {
 const loadRecs = async () => {
 try {
 await apiPost("/analysis/detect-anomalies", {});
 const data = await apiGet("/analysis/recommendations");
 setRecs(
 (data.recommendations || []).map((r) => ({
 ...r,
 done: Boolean(r.done),
 })),
 );
 } catch (error) {
 toast.error(error.message || "Failed to load recommendations");
 } finally {
 setLoading(false);
 }
 };

 loadRecs();
 }, []);

 const markDone = async (id) => {
 try {
 const updated = await apiPut(`/analysis/recommendations/${id}/toggle`);
 setRecs((current) =>
 current.map((r) =>
 r.id === id ? { ...r, ...updated, done: Boolean(updated.done) } : r,
 ),
 );
 toast.success(
 updated.done ? "Action marked as done" : "Action marked as pending",
 );
 } catch (error) {
 toast.error(error.message || "Failed to update");
 }
 };

 const filtered =
 filter === "tous"
 ? recs
 : recs.filter((r) =>
 filter === "done"
 ? r.done
 : filter === "pending"
 ? !r.done
 : r.category === filter || r.priority === filter,
 );

 const done = recs.filter((r) => r.done).length;
 const critiques = recs.filter(
 (r) => r.priority === "critique" && !r.done,
 ).length;
 const hautes = recs.filter((r) => r.priority === "haute" && !r.done).length;

 return (
 <Layout title="AI Recommendations">
 {/* Header */}
 <div className="border-b border-line pb-4 mb-6">
  <p className="micro">Action plan</p>
  <h3 className="text-[17px] font-medium text-ink mt-1">Recommendation engine</h3>
  <p className="text-[13px] leading-[1.65] text-ink-2 mt-1.5 max-w-prose">
  These recommendations are automatically generated by analyzing
  your sales, stock, and customer review data. Follow them to
  optimize your business performance.
  </p>
  <div className="mt-3 max-w-xs">
  <div className="flex items-baseline justify-between gap-3">
  <span className="micro">{done} of {recs.length} actions completed</span>
  <span className="font-mono text-[11px] tabular-nums text-ink-2">
  {recs.length ? Math.round((done / recs.length) * 100) : 0}%
  </span>
  </div>
  <div className="mt-1.5 h-px bg-line">
  <div
  className="h-px bg-ember-500 transition-all duration-500"
  style={{ width: `${recs.length ? (done / recs.length) * 100 : 0}%` }}
  />
  </div>
  </div>
 </div>

 {/* Stats */}
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
 {[
 {
 label: "Open recommendations",
 value: recs.length - done,
 color: "text-ink",
 },
 { label: "Critical — open", value: critiques, color: "text-clay" },
 { label: "High — open", value: hautes, color: "text-ember-500" },
 { label: "Completed", value: done, color: "text-olive" },
 ].map((s, i) => (
 <div
 key={i}
 className="bg-surface border hairline rounded-xs p-4 flex items-center gap-4"
 >
 <div className="flex-1 min-w-0">
 <p className="micro">{s.label}</p>
 <p className={`stat-value mt-1 ${s.color}`}>{s.value}</p>
 </div>
 </div>
 ))}
 </div>

 {/* Filters */}
 <div className="bg-surface border hairline rounded-xs p-4 mb-6">
 <div className="flex items-center gap-2 flex-wrap">
 <Filter size={14} className="text-ink-3" />
 {[
 { key: "tous", label: "All" },
 { key: "critique", label: "Critical" },
 { key: "haute", label: "High" },
 { key: "stock", label: "Stock" },
 { key: "promotion", label: "Promotion" },
 { key: "service_client", label: "Customer service" },
 { key: "pending", label: "Open" },
 { key: "done", label: "Completed" },
 ].map((f) => (
 <button
 key={f.key}
 onClick={() => setFilter(f.key)}
 className={`font-mono text-[11px] uppercase tracking-label px-3 py-1.5 rounded-xs transition-colors ${filter === f.key ? "bg-surface-2 text-ink" : "bg-canvas text-ink-3 hover:text-ink"}`}
 >
 {f.label}
 </button>
 ))}
 </div>
 </div>

 {loading && (
 <div className="bg-surface border hairline rounded-xs text-center py-12 portal-text">
 Loading recommendations…
 </div>
 )}

 {/* Recommendations */}
 <div className="space-y-4">
 {filtered.map((rec) => {
 const prio = PRIORITY_CONFIG[rec.priority] || DEFAULT_PRIORITY;
 const cat = CATEGORY_CONFIG[rec.category];
 const CatIcon = cat?.icon || Lightbulb;
 return (
 <div
 key={rec.id}
 className={`bg-surface border hairline rounded-xs p-4 animate-rise-in ${rec.done ? "opacity-60" : prio.border}`}
 >
 <div className="flex flex-col sm:flex-row gap-4">
 <div className="flex items-start gap-4 flex-1 min-w-0">
 <div className="w-9 h-9 rounded-xs bg-surface-2 border border-line flex items-center justify-center flex-shrink-0 mt-0.5">
 <CatIcon size={16} strokeWidth={1.5} className={rec.done ? "text-ink-3" : cat?.tone === "ember" ? "text-ember-500" : cat?.tone === "olive" ? "text-olive" : "text-steel"} />
 </div>
 <div className="flex-1 min-w-0">
 <div className="flex flex-wrap items-center gap-2.5 mb-2">
 <h3
 className={`text-[13px] font-medium ${rec.done ? "line-through text-ink-3" : "text-ink"}`}
 >
 {rec.title}
 </h3>
 <Status tone={prio.tone}>{prio.label}</Status>
 {cat && <Status tone={cat.tone}>{cat.label}</Status>}
 </div>
 <p className="text-[14px] leading-[1.65] text-ink-2 mb-3">
 {rec.description}
 </p>
 <div className="flex flex-col sm:flex-row flex-wrap gap-2.5">
 <div className="flex items-baseline gap-2 px-3 py-2 rounded-xs bg-canvas/60 border hairline">
 <span className="micro shrink-0">Action</span>
 <span className="text-[13px] font-medium text-ink">
 {rec.action}
 </span>
 </div>
 <div className="flex items-baseline gap-2 px-3 py-2 rounded-xs bg-canvas/60 border hairline">
 <span className="micro shrink-0">Impact</span>
 <span className={`text-[13px] font-medium ${rec.done ? "text-ink-3" : "text-olive"}`}>
 {rec.impact}
 </span>
 </div>
 </div>
 </div>
 </div>
 <div className="flex-shrink-0">
 <button
 onClick={() => markDone(rec.id)}
 className={`flex items-center gap-2 font-mono text-[11px] uppercase tracking-label px-3 py-1.5 rounded-xs border transition-colors ${
 rec.done
 ? "border-olive/40 text-olive hover:bg-olive/10"
 : "border-line text-ink-2 hover:text-ink hover:border-ink-3/50"
 }`}
 >
 <CheckCircle size={13} />
 {rec.done ? "Done" : "Mark done"}
 </button>
 </div>
 </div>
 </div>
 );
 })}
 {filtered.length === 0 && (
 <div className="bg-surface border hairline rounded-xs">
 <Empty
 title="No recommendations in this view"
 hint="New actions appear after each data sync."
 />
 </div>
 )}
 </div>
 </Layout>
 );
}
